### ISSUE TITLE
Ajouter des types d'événements

### ISSUE THREAD

**Issue by AnissElarj** [jestin-g/finDo#12]
Sur la page /events
Les événements peuvent avoir 0 ou plusieurs types d'événements associé.
![db_update.png](https://app.gitkraken.com/api/glo/boards/5f86c83d0d832b00111c5f3f/attachments/5fa718246ddf520011343355)

**Comment by jestin-g** [comment]
Infos sur la table pivot event_event_types
https://gist.github.com/Braunson/8b18b7fc7efd0890136ce5e46452ec72

**Comment by jestin-g** [comment]
Les événements possèdent bien 0 ou plusieurs types et on les affiches dans la liste des événements.
On en peut pas encore les trier par types.
