### ISSUE TITLE
Recherche d'un événement

### ISSUE THREAD

**Issue by AnissElarj** [jestin-g/finDo#13]
Composant Search :
Sur une barre de recherche disponible sur toutes les pages ,l'utilisateur peut rechercher un événement en fonction de son nom.

Recherche dynamique :
La liste des événements est affiché dynamiquement selon ce que tape l'utilisateur dans la barre de recherche.

**Comment by jestin-g** [comment]
J'ai trouvé ça, ça peut être intéressant: https://www.youtube.com/watch?v=XaHRbACplxk
