### ISSUE TITLE
Se positionner sur la carte

### ISSUE THREAD

**Issue by Clebien** [jestin-g/finDo#18]
Sur la page /map
Lorsque l'utilisateur lance la carte il voit sa position dessus et la caméra est centrée dessus.

![Map.png](https://app.gitkraken.com/api/glo/boards/5f86c83d0d832b00111c5f3f/attachments/5fb444e3d4b7f40011292f59)

**Comment by samysi** [comment]
Lorsque l'utilisateur lance la carte, un pop up lui demandant d'activer la localisation s'affiche
